# Generated by Django 5.2.15 on 2026-07-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0119_alter_stocklocation_tenant'),
        ('stock', '0123_remove_stockitem_review_needed'),
    ]

    operations = [
    ]
