# Generated by Django 5.2.15 on 2026-07-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0078_alter_address_line1_alter_address_line2'),
        ('company', '0080_company_tags'),
    ]

    operations = [
    ]
