# Generated by Django 5.2.15 on 2026-07-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0117_alter_purchaseorder_tenant_alter_returnorder_tenant_and_more'),
        ('order', '0120_purchaseorder_tags_returnorder_tags_salesorder_tags_and_more'),
    ]

    operations = [
    ]
