# Generated by Django 5.2.15 on 2026-07-06 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0121_merge_20260706_0710'),
        ('tenant', '0002_create_default_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferorder',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this order belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_orders', to='tenant.tenant', verbose_name='Tenant'),
        ),
    ]
