# Generated by Django 5.2.15 on 2026-07-08 14:20

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0122_transferorder_tenant'),
        ('stock', '0124_merge_20260706_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderlineitem',
            name='location',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Stock location from which to allocate stock for this line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='so_lines', to='stock.stocklocation', verbose_name='Stock Location'),
        ),
    ]
