# Generated by Django 5.2.15 on 2026-07-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_create_default_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['name'], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterField(
            model_name='tenant',
            name='code',
            field=models.CharField(blank=True, help_text='Optional unique code/identifier for the branch', max_length=50, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the branch', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this branch is currently active', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(help_text='Unique name for the branch', max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
